### ISSUE TITLE
리뷰 남깁니다!

### ISSUE THREAD

**Issue by gusdn0236** [devmizz/SSG-TDD#1]
좋았던 점 : 어제 회고시간에 dto 라는 부분에서 지네릭을 사용한다고 말씀해주셨는데 , 그부분이 작성되어있어서 정말 좋은 공부가 된것 같습니다!!! & 코드리뷰 남겨쥬셔서 감사합니다!!

아쉬웠던점: 제가 코드를 읽고쓰는것이 아직 많이 미숙해서 작성 해주신 코드를 제대로 이해하지 못한부분이,,, 아쉽습니다,,,,,,,,,

수고많으셨습니다!

**Comment by devmizz** [comment]
남의 코드 읽는 게 저 역시도 아직 정말 어렵습니다 ㅠㅠ 힘내보아요!
