### ISSUE TITLE
리뷰

### ISSUE THREAD

**Issue by kimdonghyeon3** [devmizz/SSG-TDD#2]
# 좋았던 점
 - 정말 클래스 분리가 세밀하게 나눠진 거 같아서 보기 편했습니다!
 -  배포까지 도전 하신 것 같아서 배포용도 훑어 보고 갑니다!

# 아쉬웠던 점
 - 개인적인 의견이긴 하지만 ...ㅎ file과 post를 나눈 이유가 무엇인지 궁금합니다!
 - 테스트 케이스에서 기본 입출력이나, util, 파일 관련 테스트가 있으면 더 좋지 않을까 의견을 남겨봅니다!

**Comment by devmizz** [comment]
- File과 Post를 나눈 게, repository를 말씀하시는 건가요? repository 나눈 걸 물어보신다면, 기본적으로 post는 프로그램 실행 중에 임시 저장소고, file은 영속성을 위한 저장소이기 때문에, 다른 저장소입니다! 그래서 둘을 분리했습니다. 이에 맞춰서 service와 controller도 분리한 것이구요!

- 의견 감사합니다! 이번엔 통합테스트만 진행해서 메서드별이나, 기본입출력 테스트는 넣질 않았네요! 다음엔 꼭 넣어보도록 하겠습니다! 좋은 의견 감사해요!
